//! `SeaORM` Entity. Generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "curation_posts")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub curation_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub post_id: Uuid,
    pub display_order: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::curations::Entity",
        from = "Column::CurationId",
        to = "super::curations::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Curations,
    #[sea_orm(
        belongs_to = "super::posts::Entity",
        from = "Column::PostId",
        to = "super::posts::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Posts,
}

impl Related<super::curations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Curations.def()
    }
}

impl Related<super::posts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Posts.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
