use utoipa::OpenApi;

#[derive(OpenApi)]
#[openapi(
    info(
        title = "DECODED API",
        version = "1.0.0",
        description = "AI 기반 미디어 디스커버리 플랫폼 API",
        contact(name = "DECODED Team")
    ),
    servers(
        (url = "https://dev.decoded.style", description = "Development server"),
        (url = "https://api.decoded.style", description = "Production server")
    ),
    paths(
        crate::handlers::health_check,
        crate::domains::users::handlers::get_user_profile,
        crate::domains::users::handlers::get_my_profile,
        crate::domains::users::handlers::update_my_profile,
        crate::domains::users::handlers::get_my_activities,
        crate::domains::users::handlers::get_my_stats,
        crate::domains::categories::handlers::get_categories,
        crate::domains::subcategories::handlers::get_all_subcategories,
        crate::domains::subcategories::handlers::get_subcategories_by_category,
        crate::domains::feed::handlers::home_feed,
        crate::domains::feed::handlers::trending,
        crate::domains::feed::handlers::list_curations,
        crate::domains::feed::handlers::curation_detail,
        crate::domains::posts::handlers::create_post_without_solutions,
        crate::domains::posts::handlers::create_post_with_solutions,
        crate::domains::posts::handlers::list_posts,
        crate::domains::posts::handlers::get_post,
        crate::domains::posts::handlers::update_post,
        crate::domains::posts::handlers::delete_post,
        crate::domains::posts::handlers::upload_image,
        crate::domains::posts::handlers::analyze_image,
        crate::domains::spots::handlers::create_spot,
        crate::domains::spots::handlers::list_spots,
        crate::domains::spots::handlers::get_spot,
        crate::domains::spots::handlers::update_spot,
        crate::domains::spots::handlers::delete_spot,
        crate::domains::solutions::handlers::create_solution,
        crate::domains::solutions::handlers::list_solutions,
        crate::domains::solutions::handlers::get_solution,
        crate::domains::solutions::handlers::update_solution,
        crate::domains::solutions::handlers::delete_solution,
        crate::domains::solutions::handlers::extract_metadata,
        crate::domains::solutions::handlers::convert_affiliate,
        crate::domains::votes::handlers::create_vote,
        crate::domains::votes::handlers::delete_vote,
        crate::domains::votes::handlers::get_vote_stats,
        crate::domains::votes::handlers::adopt_solution,
        crate::domains::votes::handlers::unadopt_solution,
        crate::domains::comments::handlers::create_comment,
        crate::domains::comments::handlers::list_comments,
        crate::domains::comments::handlers::update_comment,
        crate::domains::comments::handlers::delete_comment,
        crate::domains::badges::handlers::list_badges,
        crate::domains::badges::handlers::my_badges,
        crate::domains::badges::handlers::get_badge,
        // Search 도메인 핸들러
        crate::domains::search::handlers::search,
        crate::domains::search::handlers::search_similar,
        crate::domains::search::handlers::popular_searches,
        crate::domains::search::handlers::recent_searches,
        crate::domains::search::handlers::delete_recent_search,
        // Rankings 도메인 핸들러
        crate::domains::rankings::handlers::list_rankings,
        crate::domains::rankings::handlers::category_rankings,
        crate::domains::rankings::handlers::my_ranking_detail,
        // Earnings 도메인 핸들러
        crate::domains::earnings::handlers::create_click,
        crate::domains::earnings::handlers::get_click_stats,
        crate::domains::earnings::handlers::get_earnings,
        crate::domains::earnings::handlers::get_settlements,
        crate::domains::earnings::handlers::create_withdraw,
        crate::domains::earnings::handlers::get_withdraw_status,
        // Admin 도메인 핸들러
        crate::domains::admin::curations::create_curation,
        crate::domains::admin::curations::update_curation,
        crate::domains::admin::curations::update_curation_order,
        crate::domains::admin::curations::delete_curation,
        crate::domains::admin::synonyms::list_synonyms,
        crate::domains::admin::synonyms::create_synonym,
        crate::domains::admin::synonyms::update_synonym,
        crate::domains::admin::synonyms::delete_synonym,
        crate::domains::admin::synonyms::sync_synonyms,
        crate::domains::admin::dashboard::get_dashboard_stats,
        crate::domains::admin::dashboard::get_popular_keywords,
        crate::domains::admin::dashboard::get_traffic_analysis,
        crate::domains::admin::categories::create_category,
        crate::domains::admin::categories::update_category,
        crate::domains::admin::categories::update_category_order,
        crate::domains::admin::categories::update_category_status,
        crate::domains::admin::posts::list_posts,
        crate::domains::admin::posts::update_post_status,
        crate::domains::admin::spots::list_spots,
        crate::domains::admin::spots::update_spot_subcategory,
        crate::domains::admin::solutions::list_solutions,
        crate::domains::admin::solutions::update_solution_status,
        crate::domains::admin::badges::create_badge,
        crate::domains::admin::badges::update_badge,
        crate::domains::admin::badges::delete_badge,
        crate::domains::admin::badges::list_badges,
    ),
    tags(
        (name = "health", description = "Health check endpoints"),
        (name = "users", description = "User management"),
        (name = "categories", description = "Category management"),
        (name = "posts", description = "Post management"),
        (name = "spots", description = "Spot management"),
        (name = "solutions", description = "Solution management"),
        (name = "votes", description = "Vote and adoption"),
        (name = "comments", description = "Comment management"),
        (name = "feed", description = "Home feed and curations"),
        (name = "subcategories", description = "Subcategories"),
        (name = "search", description = "Search and feed"),
        (name = "rankings", description = "Rankings"),
        (name = "badges", description = "Badges"),
        (name = "earnings", description = "Earnings and settlements"),
        (name = "admin", description = "Admin operations"),
    ),
    components(
        schemas(
            crate::handlers::HealthResponse,
            crate::handlers::DependencyHealth,
            crate::utils::pagination::PaginationMeta,
            crate::error::ErrorResponse,
            crate::error::ErrorDetail,
            crate::domains::users::dto::UserResponse,
            crate::domains::users::dto::UpdateUserDto,
            crate::domains::users::dto::UserActivityItem,
            crate::domains::users::dto::UserActivityType,
            crate::domains::users::dto::UserStatsResponse,
            crate::domains::categories::dto::CategoryResponse,
            crate::domains::categories::dto::CategoryName,
            crate::domains::categories::dto::CategoryDescription,
            crate::domains::posts::dto::CreatePostDto,
            crate::domains::posts::dto::UpdatePostDto,
            crate::domains::posts::dto::PostResponse,
            crate::domains::posts::dto::PostDetailResponse,
            crate::domains::posts::dto::PostListItem,
            crate::domains::posts::dto::PostUserInfo,
            crate::domains::posts::dto::SpotWithTopSolution,
            crate::domains::posts::dto::TopSolutionSummary,
            crate::domains::posts::dto::MediaSourceDto,
            crate::domains::posts::dto::ImageUploadResponse,
            crate::domains::posts::dto::ImageAnalyzeResponse,
            crate::domains::posts::dto::ImageAnalysisMetadata,
                crate::domains::posts::dto::CreateSpotDto,
                crate::domains::spots::dto::CreateSpotDto,
                crate::domains::spots::dto::UpdateSpotDto,
                crate::domains::spots::dto::SpotResponse,
                crate::domains::spots::dto::SpotListItem,
                crate::domains::solutions::dto::CreateSolutionDto,
                crate::domains::solutions::dto::UpdateSolutionDto,
                crate::domains::solutions::dto::SolutionResponse,
                crate::domains::solutions::dto::SolutionListItem,
                crate::domains::solutions::dto::PriceDto,
                crate::domains::solutions::dto::VoteStatsDto,
                crate::domains::solutions::dto::ExtractMetadataDto,
                crate::domains::solutions::dto::MetadataResponse,
                crate::domains::solutions::dto::ConvertAffiliateDto,
                crate::domains::solutions::dto::AffiliateLinkResponse,
                crate::domains::subcategories::dto::SubcategoryName,
                crate::domains::subcategories::dto::SubcategoryResponse,
                crate::domains::subcategories::dto::CategoryWithSubcategories,
                crate::domains::feed::dto::FeedItem,
                crate::domains::feed::dto::FeedUser,
                crate::domains::feed::dto::MediaSource,
                crate::domains::feed::dto::FeedResponse,
                crate::domains::feed::dto::TrendingResponse,
                crate::domains::feed::dto::CurationListItem,
                crate::domains::feed::dto::CurationListResponse,
                crate::domains::feed::dto::CurationDetailResponse,
                crate::domains::votes::dto::VoteType,
                crate::domains::votes::dto::CreateVoteDto,
                crate::domains::votes::dto::VoteResponse,
                crate::domains::votes::dto::VoteStatsResponse,
                crate::domains::votes::dto::AdoptSolutionDto,
                crate::domains::votes::dto::AdoptResponse,
                crate::domains::votes::dto::UpdatedSpotInfo,
                crate::domains::comments::dto::CreateCommentDto,
                crate::domains::comments::dto::UpdateCommentDto,
                crate::domains::comments::dto::CommentResponse,
                crate::domains::comments::dto::CommentListItem,
                crate::domains::comments::dto::CommentUser,
                crate::domains::badges::dto::BadgeResponse,
                crate::domains::badges::dto::BadgeType,
                crate::domains::badges::dto::BadgeRarity,
                crate::domains::badges::dto::BadgeCriteria,
                crate::domains::badges::dto::BadgeProgress,
                crate::domains::badges::dto::EarnedBadgeItem,
                crate::domains::badges::dto::AvailableBadgeItem,
                crate::domains::badges::dto::MyBadgesResponse,
                crate::domains::badges::dto::BadgeListResponse,
                // Search 도메인 DTO
                crate::domains::search::dto::SearchQuery,
                crate::domains::search::dto::SearchResponse,
                crate::domains::search::dto::SearchResultItem,
                crate::domains::search::dto::MediaSource,
                crate::domains::search::dto::Facets,
                crate::domains::search::dto::PopularSearchResponse,
                crate::domains::search::dto::PopularSearchItem,
                crate::domains::search::dto::RecentSearchResponse,
                crate::domains::search::dto::RecentSearchItem,
                crate::domains::search::dto::SimilarSearchQuery,
                crate::domains::search::dto::SimilarSearchResponse,
                crate::domains::search::dto::SimilarSearchResultItem,
                // Rankings 도메인 DTO
                crate::domains::rankings::dto::RankingPeriodQuery,
                crate::domains::rankings::dto::RankingListResponse,
                crate::domains::rankings::dto::RankingItem,
                crate::domains::rankings::dto::RankingUser,
                crate::domains::rankings::dto::MyRanking,
                crate::domains::rankings::dto::CategoryRankingResponse,
                crate::domains::rankings::dto::CategoryRankingItem,
                crate::domains::rankings::dto::MyRankingDetailResponse,
                crate::domains::rankings::dto::SolutionStats,
                crate::domains::rankings::dto::CategoryRank,
                // Earnings 도메인 DTO
                crate::domains::earnings::dto::CreateClickDto,
                crate::domains::earnings::dto::ClickStatsResponse,
                crate::domains::earnings::dto::MonthlyClickStats,
                crate::domains::earnings::dto::EarningsResponse,
                crate::domains::earnings::dto::MonthlyEarnings,
                crate::domains::earnings::dto::SettlementsResponse,
                crate::domains::earnings::dto::SettlementItem,
                crate::domains::earnings::dto::WithdrawRequest,
                // Admin 도메인 DTO
                crate::domains::admin::curations::CurationResponse,
                crate::domains::admin::curations::CreateCurationDto,
                crate::domains::admin::curations::UpdateCurationDto,
                crate::domains::admin::curations::CurationOrderUpdate,
                crate::domains::admin::curations::CurationOrderItem,
                crate::domains::admin::synonyms::SynonymResponse,
                crate::domains::admin::synonyms::SynonymListQuery,
                crate::domains::admin::synonyms::CreateSynonymDto,
                crate::domains::admin::synonyms::UpdateSynonymDto,
                crate::domains::admin::dashboard::DashboardStatsResponse,
                crate::domains::admin::dashboard::PopularKeyword,
                crate::domains::admin::dashboard::PopularKeywordsResponse,
                crate::domains::admin::dashboard::TrafficQuery,
                crate::domains::admin::dashboard::DailyTraffic,
                crate::domains::admin::dashboard::TrafficAnalysisResponse,
                crate::domains::admin::categories::CreateCategoryDto,
                crate::domains::admin::categories::UpdateCategoryDto,
                crate::domains::admin::categories::CategoryOrderUpdate,
                crate::domains::admin::categories::CategoryOrderItem,
                crate::domains::admin::categories::CategoryStatusUpdate,
                crate::domains::admin::spots::AdminSpotListQuery,
                crate::domains::spots::dto::AdminSpotListItem,
                crate::domains::spots::dto::AdminSpotSubcategoryUpdate,
                crate::domains::admin::badges::CreateBadgeDto,
                crate::domains::admin::badges::UpdateBadgeDto,
            )
        )
)]
pub struct ApiDoc;
