# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from src.grpc.proto.inbound import inbound_pb2 as inbound_dot_inbound__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in inbound/inbound_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class QueueStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessDataBatch = channel.unary_unary(
                '/inbound.Queue/ProcessDataBatch',
                request_serializer=inbound_dot_inbound__pb2.ProcessDataBatchRequest.SerializeToString,
                response_deserializer=inbound_dot_inbound__pb2.ProcessDataBatchResponse.FromString,
                _registered_method=True)
        self.ExtractOGData = channel.unary_unary(
                '/inbound.Queue/ExtractOGData',
                request_serializer=inbound_dot_inbound__pb2.ExtractOGDataRequest.SerializeToString,
                response_deserializer=inbound_dot_inbound__pb2.ExtractOGDataResponse.FromString,
                _registered_method=True)
        self.AnalyzeLink = channel.unary_unary(
                '/inbound.Queue/AnalyzeLink',
                request_serializer=inbound_dot_inbound__pb2.AnalyzeLinkRequest.SerializeToString,
                response_deserializer=inbound_dot_inbound__pb2.AnalyzeLinkResponse.FromString,
                _registered_method=True)
        self.AnalyzeLinkDirect = channel.unary_unary(
                '/inbound.Queue/AnalyzeLinkDirect',
                request_serializer=inbound_dot_inbound__pb2.AnalyzeLinkRequest.SerializeToString,
                response_deserializer=inbound_dot_inbound__pb2.AnalyzeLinkDirectResponse.FromString,
                _registered_method=True)
        self.AnalyzeImage = channel.unary_unary(
                '/inbound.Queue/AnalyzeImage',
                request_serializer=inbound_dot_inbound__pb2.AnalyzeImageRequest.SerializeToString,
                response_deserializer=inbound_dot_inbound__pb2.AnalyzeImageResponse.FromString,
                _registered_method=True)
        self.ProcessPostEditorial = channel.unary_unary(
                '/inbound.Queue/ProcessPostEditorial',
                request_serializer=inbound_dot_inbound__pb2.ProcessPostEditorialRequest.SerializeToString,
                response_deserializer=inbound_dot_inbound__pb2.ProcessPostEditorialResponse.FromString,
                _registered_method=True)
        self.ExtractPostContext = channel.unary_unary(
                '/inbound.Queue/ExtractPostContext',
                request_serializer=inbound_dot_inbound__pb2.ExtractPostContextRequest.SerializeToString,
                response_deserializer=inbound_dot_inbound__pb2.ExtractPostContextResponse.FromString,
                _registered_method=True)


class QueueServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ProcessDataBatch(self, request, context):
        """Existing batch processing
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExtractOGData(self, request, context):
        """New separated flow methods
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeLink(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeLinkDirect(self, request, context):
        """Direct Analysis (Synchronous/No-Batch) for Testing/Immediate updates
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeImage(self, request, context):
        """Image analysis - direct response (synchronous)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessPostEditorial(self, request, context):
        """Post editorial - enqueue to job queue (asynchronous)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExtractPostContext(self, request, context):
        """Extract context and style tags from post image (synchronous, Ollama local inference)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QueueServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessDataBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessDataBatch,
                    request_deserializer=inbound_dot_inbound__pb2.ProcessDataBatchRequest.FromString,
                    response_serializer=inbound_dot_inbound__pb2.ProcessDataBatchResponse.SerializeToString,
            ),
            'ExtractOGData': grpc.unary_unary_rpc_method_handler(
                    servicer.ExtractOGData,
                    request_deserializer=inbound_dot_inbound__pb2.ExtractOGDataRequest.FromString,
                    response_serializer=inbound_dot_inbound__pb2.ExtractOGDataResponse.SerializeToString,
            ),
            'AnalyzeLink': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeLink,
                    request_deserializer=inbound_dot_inbound__pb2.AnalyzeLinkRequest.FromString,
                    response_serializer=inbound_dot_inbound__pb2.AnalyzeLinkResponse.SerializeToString,
            ),
            'AnalyzeLinkDirect': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeLinkDirect,
                    request_deserializer=inbound_dot_inbound__pb2.AnalyzeLinkRequest.FromString,
                    response_serializer=inbound_dot_inbound__pb2.AnalyzeLinkDirectResponse.SerializeToString,
            ),
            'AnalyzeImage': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeImage,
                    request_deserializer=inbound_dot_inbound__pb2.AnalyzeImageRequest.FromString,
                    response_serializer=inbound_dot_inbound__pb2.AnalyzeImageResponse.SerializeToString,
            ),
            'ProcessPostEditorial': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessPostEditorial,
                    request_deserializer=inbound_dot_inbound__pb2.ProcessPostEditorialRequest.FromString,
                    response_serializer=inbound_dot_inbound__pb2.ProcessPostEditorialResponse.SerializeToString,
            ),
            'ExtractPostContext': grpc.unary_unary_rpc_method_handler(
                    servicer.ExtractPostContext,
                    request_deserializer=inbound_dot_inbound__pb2.ExtractPostContextRequest.FromString,
                    response_serializer=inbound_dot_inbound__pb2.ExtractPostContextResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'inbound.Queue', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('inbound.Queue', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Queue(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProcessDataBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inbound.Queue/ProcessDataBatch',
            inbound_dot_inbound__pb2.ProcessDataBatchRequest.SerializeToString,
            inbound_dot_inbound__pb2.ProcessDataBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExtractOGData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inbound.Queue/ExtractOGData',
            inbound_dot_inbound__pb2.ExtractOGDataRequest.SerializeToString,
            inbound_dot_inbound__pb2.ExtractOGDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnalyzeLink(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inbound.Queue/AnalyzeLink',
            inbound_dot_inbound__pb2.AnalyzeLinkRequest.SerializeToString,
            inbound_dot_inbound__pb2.AnalyzeLinkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnalyzeLinkDirect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inbound.Queue/AnalyzeLinkDirect',
            inbound_dot_inbound__pb2.AnalyzeLinkRequest.SerializeToString,
            inbound_dot_inbound__pb2.AnalyzeLinkDirectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnalyzeImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inbound.Queue/AnalyzeImage',
            inbound_dot_inbound__pb2.AnalyzeImageRequest.SerializeToString,
            inbound_dot_inbound__pb2.AnalyzeImageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessPostEditorial(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inbound.Queue/ProcessPostEditorial',
            inbound_dot_inbound__pb2.ProcessPostEditorialRequest.SerializeToString,
            inbound_dot_inbound__pb2.ProcessPostEditorialResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExtractPostContext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inbound.Queue/ExtractPostContext',
            inbound_dot_inbound__pb2.ExtractPostContextRequest.SerializeToString,
            inbound_dot_inbound__pb2.ExtractPostContextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class RawPostsWorkerStub(object):
    """#258 Raw Posts worker — api-server calls ai-server to enqueue a scrape job.
    ai-server's ARQ worker picks up the job, scrapes via adapter, uploads to R2,
    then calls back api-server's RawPostsCallback.ReportRawPostsFetched.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EnqueueFetchRawPosts = channel.unary_unary(
                '/inbound.RawPostsWorker/EnqueueFetchRawPosts',
                request_serializer=inbound_dot_inbound__pb2.EnqueueFetchRawPostsRequest.SerializeToString,
                response_deserializer=inbound_dot_inbound__pb2.EnqueueFetchRawPostsResponse.FromString,
                _registered_method=True)


class RawPostsWorkerServicer(object):
    """#258 Raw Posts worker — api-server calls ai-server to enqueue a scrape job.
    ai-server's ARQ worker picks up the job, scrapes via adapter, uploads to R2,
    then calls back api-server's RawPostsCallback.ReportRawPostsFetched.
    """

    def EnqueueFetchRawPosts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RawPostsWorkerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EnqueueFetchRawPosts': grpc.unary_unary_rpc_method_handler(
                    servicer.EnqueueFetchRawPosts,
                    request_deserializer=inbound_dot_inbound__pb2.EnqueueFetchRawPostsRequest.FromString,
                    response_serializer=inbound_dot_inbound__pb2.EnqueueFetchRawPostsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'inbound.RawPostsWorker', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('inbound.RawPostsWorker', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RawPostsWorker(object):
    """#258 Raw Posts worker — api-server calls ai-server to enqueue a scrape job.
    ai-server's ARQ worker picks up the job, scrapes via adapter, uploads to R2,
    then calls back api-server's RawPostsCallback.ReportRawPostsFetched.
    """

    @staticmethod
    def EnqueueFetchRawPosts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inbound.RawPostsWorker/EnqueueFetchRawPosts',
            inbound_dot_inbound__pb2.EnqueueFetchRawPostsRequest.SerializeToString,
            inbound_dot_inbound__pb2.EnqueueFetchRawPostsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
