from pydantic import BaseModel, HttpUrl, field_validator
from typing import Dict, List, Optional, Literal, Union
from enum import Enum


class DataItemType(str, Enum):
    LINK = "link"
    IMAGE = "image"


class DataItem(BaseModel):
    item_id: str
    type: DataItemType
    # oneof data_source - exactly one of these should be provided
    url: Optional[str] = None           # URL 방식 (링크 또는 이미지 URL)
    image_data: Optional[bytes] = None  # 바이너리 데이터 방식 (업로드된 이미지)
    existing_metadata: Optional[Dict[str, str]] = None
    post_id: Optional[str] = None       # Solution ID for backend callback (deprecated: use item_id instead)
    
    @field_validator('image_data', 'url')
    @classmethod
    def validate_data_source(cls, v, info):
        """oneof 필드 검증: url 또는 image_data 중 정확히 하나만 설정되어야 함"""
        values = info.data
        field_name = info.field_name
        
        url = values.get('url') if field_name == 'image_data' else v
        image_data = values.get('image_data') if field_name == 'url' else v
        
        # 정확히 하나만 설정되어야 함
        has_url = url is not None
        has_image_data = image_data is not None
        
        if not has_url and not has_image_data:
            raise ValueError('url 또는 image_data 중 하나는 반드시 설정되어야 합니다')
        
        if has_url and has_image_data:
            raise ValueError('url과 image_data는 동시에 설정될 수 없습니다 (oneof 필드)')
        
        return v
    
    def get_data_source_type(self) -> str:
        """현재 설정된 데이터 소스 타입 반환"""
        if self.url is not None:
            return "url"
        elif self.image_data is not None:
            return "image_data"
        else:
            return "none"


# LinkResult and ImageResult models have been replaced by:
# - LinkProcessingResult and ImageProcessingResult in src.database.models.content
# These old models are kept temporarily for compatibility during migration


class BatchStatistics(BaseModel):
    total_count: int
    success_count: int
    partial_count: int
    failed_count: int
    processing_time_seconds: float


class ProcessedDataBatch(BaseModel):
    batch_id: str
    link_results: List  # Now List[LinkProcessingResult] 
    image_results: List  # Now List[ImageProcessingResult]
    statistics: BatchStatistics


class ProcessDataBatchRequest(BaseModel):
    batch_id: str  # Generated by server
    items: List[DataItem]


class ProcessDataBatchResponse(BaseModel):
    success: bool
    message: str
    batch_id: str